Repository kubescape/opa-utils, pull requests merged in 2024-02, with the labels that each got.

#147 Check string before converting
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
  go.mod
  go.sum
  objectsenvelopes/regoresponsevectorobject.go
  objectsenvelopes/regoresponsevectorobject_test.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#149 Fixed exceptions in vector objects
  exceptions/comparator.go
  exceptions/comparator_test.go
  exceptions/designators_cache.go
  exceptions/exceptionprocessor.go
  exceptions/exceptionprocessor_test.go
Labels: enhancement, bug_fix, tests, Review effort [1-5]: 3

#148 feat: Add Vulnerability scanning report to the summaryDetails section
  reporthandling/results/v1/reportsummary/datastructures.go
Labels: enhancement, Review effort [1-5]: 2
